python profiling-recipe/profiles/profiling_pipeline.py --config config_files/config_compounds.yml
python profiling-recipe/profiles/profiling_pipeline.py --config config_files/config_crispr.yml
python profiling-recipe/profiles/profiling_pipeline.py --config config_files/config_orf.yml
python profiling-recipe/profiles/profiling_pipeline.py --config config_files/config_compounds_crispr_orf_feature_select.yml
python profiling-recipe/profiles/profiling_pipeline.py --config config_files/config_bleaching.yml
python profiling-recipe/profiles/profiling_pipeline.py --config config_files/config_timepoint.yml
python profiling-recipe/profiles/profiling_pipeline.py --config config_files/config_compounds_dl.yml
python profiling-recipe/profiles/profiling_pipeline.py --config config_files/config_crispr_dl.yml
python profiling-recipe/profiles/profiling_pipeline.py --config config_files/config_orf_dl.yml
